# Generated by Django 6.0.7 on 2026-08-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_student', to='core.studentapplication'),
        ),
        migrations.AddField(
            model_name='student',
            name='financial_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_financial_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_fully_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('dropped', 'Dropped'), ('suspended', 'Suspended'), ('pending_clearance', 'Pending Clearance'), ('pending_registration', 'Pending Registration')], default='pending_registration', max_length=30),
        ),
    ]
