# Generated by Django 6.0.7 on 2026-07-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(blank=True, max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmittedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('admission_letter_sent', models.BooleanField(default=False)),
                ('admission_letter_date', models.DateField(blank=True, null=True)),
                ('confirmed_enrollment', models.BooleanField(default=False)),
                ('confirmed_enrollment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.admissionbatch')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_students', to='core.studentapplication')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_record', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2'), ('semester3', 'Semester 3'), ('trimester1', 'Trimester 1'), ('trimester2', 'Trimester 2'), ('trimester3', 'Trimester 3')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('registration_deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='admissions.academicyear')),
            ],
        ),
    ]
