# Generated by Django 6.0.7 on 2026-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='custom_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
